### PR TITLE
PBR rendering and various improvements 

### PR DESCRIPTION
**Pull request by MichaelMoroz**
I thought I'd add PBR rendering and see how it would look like. In some cases the fractals look awesome, in others not so much. I guess each level should have their own metallic and roughness coefficient for best looks. Probably using an orbit trap to generate the coefficients would look even better, but I haven't tried it yet.
Here are some example screenshots with 0.6 metallic and 0.3 roughness:

Roughness 0.8 and 0.1 metallic:

### CODE REVIEW

**Comment by MichaelMoroz** [comment]
On most levels
```
#define PBR_METALLIC 0.5
#define PBR_ROUGHNESS 0.35
```
looks best

**Comment by MichaelMoroz** [comment]
Added physically correct refraction and reflection, and tried to solve the flickering camera problem.
Now the camera has a finite size, І guess this is also not exactly good, since we can't zoom to the fractal as close as we want.
Another way to solve this would be to probably to do camera collision detection, but then we wouldn't be able to cross the fractal.
Seems like a lose-lose situation to me.

**Comment by Ekozmaster** [comment]
Awesome work. I was tweaking the shaders a little then found your pull request. It works just awesome.
I rather like the fractals opaque, non-metallic, with mettalic = 0 and roughness = 1 or something around, as it emphasizes the wonderful architectural or even organic natures of fractals, at least for me.
With that, "Build up Speed" looks like a giant iceberg.
There are few things i noticed that can be fixed or improved:

1. It seens like fog isn't working with this shader.
2. You don't need to ask for shadows if the surface isn't facing the light. Saves some marches and allows my GPU to lock at 60fps when looking at a giant wall which isn't facing LIGHT_DIRECTION.
3. Maybe, with access to the marble's rotation and a texture slot, you can implement a triplanar mapping to put skins on marbles :) (I think i might put that on issues session).

**Comment by MichaelMoroz** [comment]
> 1. It seens like fog isn't working with this shader.

I know, I did not see any reason to add it, for me it looked meh. But it's not too hard.

> 2. You don't need to ask for shadows if the surface isn't facing the light. Saves some marches and allows my GPU to lock at 60fps when looking at a giant wall which isn't facing LIGHT_DIRECTION.

I also knew about that, but in the case of marching towards the surface it will stop only after 1 march.
I assumed that saving only 1 march would not make any difference.

> 3. Maybe, with access to the marble's rotation and a texture slot, you can implement a triplanar mapping to put skins on marbles :) (I think i might put that on issues session).

That would require to add rotation physics to the engine, the marble is currently only a material point.
Textures are unnecessary, you can make a fractal pattern on the surface with a simple formula.

**Comment by MichaelMoroz** [comment]
OK, I solved issues #42 and #43.
+ The window is now re-sizable. The game is forced to use a rendering texture all the time now.
+ Screenshot capture on F5. It will work only if the folder "screenshots" exists! Also the screenshot numbering resets at each game launch currently.
The screenshot is captured at 4x the current rendering resolution and is clamped at 4K. My Windows tablet crashes when tying to render at 4K actually(yeah, a tablet is somewhat capable of running Marble Marcher at potato mode, lol), that's why the resolution isn't 4K all the time.
Here are some example 4K screenshots:






Here is the compiled version: [v1.1.2alpha](https://github.com/MichaelMoroz/MarbleMarcher/releases/tag/v1.1.2alpha)

Also, I will be making more drastic changes to the game in my [sandbox branch](https://github.com/MichaelMoroz/MarbleMarcher/tree/sandbox). I'm planning to add a level editor and rewriting the rendering engine completely(you can get probably 5x more fps with the right implementation).

**Comment by MichaelMoroz** [comment]
Also some screenshots without PBR:

**Comment by JimmyCushnie** [comment]
Excellent work @MichaelMoroz, that looks awesome! I will be watching your fork with great interest.

Rather than hardcoding the screenshot size, do you think it would be possible to make it configurable from a txt file?

**Comment by MichaelMoroz** [comment]
> Rather than hardcoding the screenshot size, do you think it would be possible to make it configurable from a txt file?

I thought about that, but I assumed making a separate settings menu in the game would be better. 
Sadly it requires a lot of work to make from scratch. It's a lot easier with AntTweakBar though, so I will probably just add a resolution variable to the settings bar, but only on my fork.
On this branch though, a txt file would be the only solution it seems.

**Comment by MichaelMoroz** [comment]
I added a config.txt file. Now it only has the screenshot size, but in the future there might be graphics settings or more.
[1.1.2alpha2](https://github.com/MichaelMoroz/MarbleMarcher/releases/tag/v1.1.2alpha2)

**Comment by MichaelMoroz** [comment]
I've optimized the fractal DE function, turns out it was calculating the same trigonometric function every iteration and march, I replaced it so it calculates trigonometric functions only 4 times per pixel, instead of 100+ times. It should give at least a 10% performance boost, depending on how well your GPU is capable of computing sin and cos(the better the smaller the fps boost).
[alpha3](https://github.com/MichaelMoroz/MarbleMarcher/releases/tag/v1.1.2alpha3)

**Comment by DangerCow** [comment]
why hasent this been merged? id love to see it in a new update

**Comment by MichaelMoroz** [comment]
This repository is no longer maintained, all new versions will be in the community edition repo.

**Comment by mygizli04** [comment]
@MichaelMoroz What is "the community edition" repo?

**Comment by WAUthethird** [comment]
> @MichaelMoroz What is "the community edition" repo?


@mygizli04 The link is in the [README](https://github.com/HackerPoet/MarbleMarcher/blob/master/README.md#no-further-development-planned), but here's the link anyways: [https://github.com/WAUthethird/Marble-Marcher-Community-Edition](https://github.com/WAUthethird/Marble-Marcher-Community-Edition)

**Pull request closed without merging**
