### PR TITLE
added 4k support

### PR DESCRIPTION
**Pull request by JimmyCushnie**
Added 4k support

### CODE REVIEW

**Comment by HackerPoet** [comment]
I don't think any machine can run 4K at full framerate. These high resolutions can even crash slower computers.  Also, adding a new resolution requires a layout change to the selection menu which would need to be made to have it selectable and not interfere with the other options.

**Comment by JimmyCushnie** [comment]
> I don't think any machine can run 4K at full framerate.

I mainly want this for wallpaper generation tbh

**Comment by HackerPoet** [comment]
Adding a screenshot key in-game would a better way to do it. It could render just that one frame in super high resolution.

**Comment by JimmyCushnie** [comment]
In that case, I'm going to close this PR and open an issue requesting that feature.

**Comment by JimmyCushnie** [comment]
It's worth mentioning that supporting higher resolutions (as in, the UI would automatically adjust appropriately rather than needing to be specifically configured for each resolution) would give the game better forwards compatibility. 20 years from now when my monitor is 16k, it would be nice to be able to run Marble Marcher at that resolution.

Though with the game being open source, I suppose future people can worry about that problem.

**Pull request closed without merging**
