### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by jgoldfar**
Possible partial solution to #6 and #7? I can push an update to the branch to give the correct link for your CI if you'd like to turn CI for the repo on

### CODE REVIEW

**Comment by jgoldfar** [comment]
I've only tinkered with CircleCI a couple of times (and I have no idea how "standard" Linux packaging should be done, unless creating a tarball suffices,) but one can easily push a build artifact to Github as a release (for tagged versions)

**Comment by jgoldfar** [comment]
This is now also working on OSX, so issues like #9 can hopefully be fixed in a reproducible way

**Comment by vikrambombhi** [comment]
not sure if pushing as a GitHub release is super simple. Can you try getting it to work and report back?

**Comment by jgoldfar** [comment]
Seems to work fine (see https://github.com/jgoldfar/MarbleMarcher/releases) though some of the settings will have to be tweaked for it to release from this repo, and from the master branch, etc.

**Comment by HackerPoet** [comment]
I'm not familiar with Travis CI, but I like the idea that it can cross compile for the other platforms.  It would be great to add Mac and Linux versions to the itch.io page.  I noticed that the tarballs seem to also include source for the dependencies, is that really necessary?

**Comment by HackerPoet** [comment]
Thanks, merging.

**Comment by HackerPoet** [comment]
How do I get it to rebuild after pushing?

**Comment by jgoldfar** [comment]
There should be a UI option on Travis to restart a given job, and I believe the release provider is set to overwrite any previous releases. Are you having trouble getting it to push back to this repository’s releases? It will need a new API key AFAIK

**Pull request merged**
